from typing import Any, Awaitable, Callable, Dict, List

from mcp.types import TextContent

from .automod_policy import (
    handle_automod_apply_ruleset,
    handle_automod_get_ruleset,
    handle_automod_rollback_ruleset,
    handle_automod_validate_ruleset,
)
from .channels import (
    handle_create_text_channel,
    handle_delete_channel,
    handle_get_channels,
)
from .forums import (
    handle_add_thread_tags,
    handle_list_threads,
    handle_read_forum_threads,
    handle_search_threads,
    handle_unarchive_thread,
)
from .forum_intel import (
    handle_get_thread_activity_summary,
    handle_get_thread_context,
    handle_list_forum_posts,
    handle_list_thread_participants,
    handle_read_forum_post_messages,
    handle_read_forum_posts_batch,
    handle_retag_forum_post,
    handle_tag_forum_post,
)
from .expansion_fillers import (
    handle_append_incident_event,
    handle_automod_export_rules,
    handle_bulk_ban_members,
    handle_close_incident,
    handle_create_auto_moderation_rule,
    handle_create_category,
    handle_create_incident_room,
    handle_delete_category,
    handle_list_auto_moderation_rules,
    handle_move_category,
    handle_prune_inactive_members,
    handle_remove_member_timeout,
    handle_rename_category,
    handle_unban_member,
    handle_update_auto_moderation_rule,
)
from .inventory import (
    handle_diff_channel_permissions,
    handle_export_server_snapshot,
    handle_get_channel_hierarchy,
    handle_get_channel_type_counts,
    handle_get_channels_structured,
    handle_get_permission_overwrites,
    handle_get_role_hierarchy,
    handle_list_inactive_channels,
)
from .messages import handle_edit_message, handle_read_messages, handle_send_message
from .moderation_core import (
    handle_moderation_ban_member,
    handle_moderation_bulk_delete,
    handle_moderation_kick_member,
    handle_moderation_timeout_member,
)
from .messaging_workflow import (
    handle_create_channel_webhook,
    handle_crosspost_announcement,
    handle_execute_channel_webhook,
    handle_get_guild_vanity_url,
    handle_list_channel_webhooks,
    handle_list_guild_integrations,
    handle_send_embed_message,
    handle_send_rich_announcement,
)
from .misc import (
    handle_add_multiple_reactions,
    handle_add_reaction,
    handle_download_attachment,
    handle_get_user_info,
    handle_moderate_message,
    handle_remove_reaction,
)
from .role_governance import (
    handle_add_roles_bulk,
    handle_create_role,
    handle_delete_role,
    handle_mute_member_role_based,
    handle_permission_drift_check,
    handle_remove_roles_bulk,
    handle_unmute_member_role_based,
    handle_update_role,
)
from .onboarding import (
    handle_dynamic_role_provision,
    handle_get_guild_onboarding,
    handle_get_guild_welcome_screen,
    handle_onboarding_friction_audit,
    handle_progressive_access_unlock,
    handle_update_guild_onboarding,
    handle_update_guild_welcome_screen,
    handle_verification_gate_orchestrator,
)
from .incident_ops import (
    handle_incident_apply_lockdown,
    handle_incident_get_channel_state,
    handle_incident_rollback_lockdown,
    handle_incident_set_channel_state,
)
from .roles import handle_add_role, handle_remove_role
from .audit_analytics import (
    handle_check_audit_reason_compliance,
    handle_get_audit_actor_summary,
    handle_get_audit_log,
    handle_get_channel_activity_summary,
    handle_get_incident_timeline,
    handle_get_member_moderation_history,
    handle_governance_evidence_packager,
    handle_server_health_check,
)
from .server_info import (
    handle_get_server_info,
    handle_list_members,
    handle_list_servers,
)
from .topology import (
    handle_topology_channel_children,
    handle_topology_channel_tree,
    handle_topology_permission_matrix,
    handle_topology_role_hierarchy,
)


Handler = Callable[[Dict[str, Any], Dict[str, Any]], Awaitable[List[TextContent]]]


TOOL_ROUTER: Dict[str, Handler] = {
    "send_message": handle_send_message,
    "send-message": handle_send_message,
    "read_messages": handle_read_messages,
    "read-messages": handle_read_messages,
    "edit_message": handle_edit_message,
    "edit-message": handle_edit_message,
    "read_forum_threads": handle_read_forum_threads,
    "read-forum-threads": handle_read_forum_threads,
    "list_threads": handle_list_threads,
    "list-threads": handle_list_threads,
    "search_threads": handle_search_threads,
    "search-threads": handle_search_threads,
    "add_thread_tags": handle_add_thread_tags,
    "add-thread-tags": handle_add_thread_tags,
    "unarchive_thread": handle_unarchive_thread,
    "unarchive-thread": handle_unarchive_thread,
    "list_forum_posts": handle_list_forum_posts,
    "read_forum_post_messages": handle_read_forum_post_messages,
    "read_forum_posts_batch": handle_read_forum_posts_batch,
    "get_thread_context": handle_get_thread_context,
    "list_thread_participants": handle_list_thread_participants,
    "get_thread_activity_summary": handle_get_thread_activity_summary,
    "tag_forum_post": handle_tag_forum_post,
    "retag_forum_post": handle_retag_forum_post,
    "moderation_bulk_delete": handle_moderation_bulk_delete,
    "moderation_timeout_member": handle_moderation_timeout_member,
    "moderation_kick_member": handle_moderation_kick_member,
    "moderation_ban_member": handle_moderation_ban_member,
    "topology_channel_tree": handle_topology_channel_tree,
    "topology_channel_children": handle_topology_channel_children,
    "topology_role_hierarchy": handle_topology_role_hierarchy,
    "topology_permission_matrix": handle_topology_permission_matrix,
    "download_attachment": handle_download_attachment,
    "download-attachment": handle_download_attachment,
    "get_user_info": handle_get_user_info,
    "moderate_message": handle_moderate_message,
    "get_server_info": handle_get_server_info,
    "get_channels": handle_get_channels,
    "list_members": handle_list_members,
    "add_role": handle_add_role,
    "remove_role": handle_remove_role,
    "create_text_channel": handle_create_text_channel,
    "delete_channel": handle_delete_channel,
    "add_reaction": handle_add_reaction,
    "add_multiple_reactions": handle_add_multiple_reactions,
    "remove_reaction": handle_remove_reaction,
    "get_guild_welcome_screen": handle_get_guild_welcome_screen,
    "update_guild_welcome_screen": handle_update_guild_welcome_screen,
    "get_guild_onboarding": handle_get_guild_onboarding,
    "update_guild_onboarding": handle_update_guild_onboarding,
    "dynamic_role_provision": handle_dynamic_role_provision,
    "verification_gate_orchestrator": handle_verification_gate_orchestrator,
    "progressive_access_unlock": handle_progressive_access_unlock,
    "onboarding_friction_audit": handle_onboarding_friction_audit,
    "send_embed_message": handle_send_embed_message,
    "send_rich_announcement": handle_send_rich_announcement,
    "crosspost_announcement": handle_crosspost_announcement,
    "create_channel_webhook": handle_create_channel_webhook,
    "list_channel_webhooks": handle_list_channel_webhooks,
    "execute_channel_webhook": handle_execute_channel_webhook,
    "list_guild_integrations": handle_list_guild_integrations,
    "get_guild_vanity_url": handle_get_guild_vanity_url,
    "list_servers": handle_list_servers,
    "get_channels_structured": handle_get_channels_structured,
    "get_channel_hierarchy": handle_get_channel_hierarchy,
    "get_role_hierarchy": handle_get_role_hierarchy,
    "get_permission_overwrites": handle_get_permission_overwrites,
    "diff_channel_permissions": handle_diff_channel_permissions,
    "export_server_snapshot": handle_export_server_snapshot,
    "get_channel_type_counts": handle_get_channel_type_counts,
    "list_inactive_channels": handle_list_inactive_channels,
    "create_role": handle_create_role,
    "delete_role": handle_delete_role,
    "update_role": handle_update_role,
    "add_roles_bulk": handle_add_roles_bulk,
    "remove_roles_bulk": handle_remove_roles_bulk,
    "mute_member_role_based": handle_mute_member_role_based,
    "unmute_member_role_based": handle_unmute_member_role_based,
    "permission_drift_check": handle_permission_drift_check,
    "get_audit_log": handle_get_audit_log,
    "get_member_moderation_history": handle_get_member_moderation_history,
    "get_channel_activity_summary": handle_get_channel_activity_summary,
    "get_incident_timeline": handle_get_incident_timeline,
    "get_audit_actor_summary": handle_get_audit_actor_summary,
    "check_audit_reason_compliance": handle_check_audit_reason_compliance,
    "server_health_check": handle_server_health_check,
    "governance_evidence_packager": handle_governance_evidence_packager,
    "incident_get_channel_state": handle_incident_get_channel_state,
    "incident-get-channel-state": handle_incident_get_channel_state,
    "incident_set_channel_state": handle_incident_set_channel_state,
    "incident-set-channel-state": handle_incident_set_channel_state,
    "incident_apply_lockdown": handle_incident_apply_lockdown,
    "incident-apply-lockdown": handle_incident_apply_lockdown,
    "incident_rollback_lockdown": handle_incident_rollback_lockdown,
    "incident-rollback-lockdown": handle_incident_rollback_lockdown,
    "automod_validate_ruleset": handle_automod_validate_ruleset,
    "automod-validate-ruleset": handle_automod_validate_ruleset,
    "automod_get_ruleset": handle_automod_get_ruleset,
    "automod-get-ruleset": handle_automod_get_ruleset,
    "automod_apply_ruleset": handle_automod_apply_ruleset,
    "automod-apply-ruleset": handle_automod_apply_ruleset,
    "automod_rollback_ruleset": handle_automod_rollback_ruleset,
    "automod-rollback-ruleset": handle_automod_rollback_ruleset,
    "bulk_ban_members": handle_bulk_ban_members,
    "prune_inactive_members": handle_prune_inactive_members,
    "remove_member_timeout": handle_remove_member_timeout,
    "unban_member": handle_unban_member,
    "create_category": handle_create_category,
    "rename_category": handle_rename_category,
    "move_category": handle_move_category,
    "delete_category": handle_delete_category,
    "create_incident_room": handle_create_incident_room,
    "append_incident_event": handle_append_incident_event,
    "close_incident": handle_close_incident,
    "list_auto_moderation_rules": handle_list_auto_moderation_rules,
    "create_auto_moderation_rule": handle_create_auto_moderation_rule,
    "update_auto_moderation_rule": handle_update_auto_moderation_rule,
    "automod_export_rules": handle_automod_export_rules,
}


async def dispatch_tool_call(
    name: str, arguments: Dict[str, Any], deps: Dict[str, Any]
) -> List[TextContent]:
    handler = TOOL_ROUTER.get(name)
    if handler is None:
        raise ValueError(f"Unknown tool: {name}")
    return await handler(arguments, deps)
