from typing import Any, Awaitable, Callable, Dict, List

from mcp.types import TextContent

from .automod_policy import (
    handle_automod_apply_ruleset,
    handle_automod_get_ruleset,
    handle_automod_rollback_ruleset,
    handle_automod_validate_ruleset,
)
from .channels import (
    handle_create_forum_channel,
    handle_create_voice_channel,
    handle_create_text_channel,
    handle_delete_channel,
    handle_get_channels,
    handle_update_forum_channel,
    handle_update_text_channel,
    handle_update_voice_channel,
)
from .forums import (
    handle_add_thread_tags,
    handle_list_threads,
    handle_read_forum_threads,
    handle_search_threads,
    handle_unarchive_thread,
)
from .forum_intel import (
    handle_get_thread_activity_summary,
    handle_get_thread_context,
    handle_list_forum_posts,
    handle_list_thread_participants,
    handle_read_forum_post_messages,
    handle_read_forum_posts_batch,
    handle_retag_forum_post,
    handle_tag_forum_post,
)
from .expansion_fillers import (
    handle_append_incident_event,
    handle_automod_export_rules,
    handle_bulk_ban_members,
    handle_close_incident,
    handle_create_auto_moderation_rule,
    handle_create_category,
    handle_create_incident_room,
    handle_delete_category,
    handle_delete_auto_moderation_rule,
    handle_list_auto_moderation_rules,
    handle_move_category,
    handle_prune_inactive_members,
    handle_remove_member_timeout,
    handle_rename_category,
    handle_unban_member,
    handle_update_auto_moderation_rule,
)
from .inventory import (
    handle_diff_channel_permissions,
    handle_export_server_snapshot,
    handle_get_channel_hierarchy,
    handle_get_channel_type_counts,
    handle_get_channels_structured,
    handle_get_permission_overwrites,
    handle_remove_channel_permission_overwrite,
    handle_set_channel_permission_overwrite,
    handle_get_role_hierarchy,
    handle_list_inactive_channels,
)
from .emoji import handle_list_guild_emojis
from .mass_mentions import handle_audit_mass_mentions
from .member_admin import handle_set_member_nickname, handle_set_member_roles
from .messages import (
    handle_edit_message,
    handle_read_messages,
    handle_reply_message,
    handle_send_message,
)
from .moderation_core import (
    handle_moderation_ban_member,
    handle_moderation_bulk_delete,
    handle_moderation_kick_member,
    handle_moderation_timeout_member,
)
from .messaging_workflow import (
    handle_create_channel_webhook,
    handle_crosspost_announcement,
    handle_execute_channel_webhook,
    handle_get_guild_vanity_url,
    handle_list_channel_webhooks,
    handle_list_guild_integrations,
    handle_send_embed_message,
    handle_send_rich_announcement,
)
from .misc import (
    handle_add_multiple_reactions,
    handle_add_reaction,
    handle_download_attachment,
    handle_get_user_info,
    handle_moderate_message,
    handle_remove_reaction,
)
from .role_governance import (
    handle_add_roles_bulk,
    handle_create_role,
    handle_delete_role,
    handle_mute_member_role_based,
    handle_permission_drift_check,
    handle_remove_roles_bulk,
    handle_unmute_member_role_based,
    handle_update_role,
)
from .onboarding import (
    handle_dynamic_role_provision,
    handle_get_guild_onboarding,
    handle_get_guild_welcome_screen,
    handle_onboarding_friction_audit,
    handle_progressive_access_unlock,
    handle_update_guild_onboarding,
    handle_update_guild_welcome_screen,
    handle_verification_gate_orchestrator,
)
from .permission_intel import (
    handle_compute_member_permissions,
    handle_get_role_permissions,
)
from .incident_ops import (
    handle_incident_apply_lockdown,
    handle_incident_get_channel_state,
    handle_incident_rollback_lockdown,
    handle_incident_set_channel_state,
)
from .roles import handle_add_role, handle_remove_role
from .audit_analytics import (
    handle_check_audit_reason_compliance,
    handle_get_audit_actor_summary,
    handle_get_audit_log,
    handle_get_channel_activity_summary,
    handle_get_incident_timeline,
    handle_get_member_moderation_history,
    handle_governance_evidence_packager,
    handle_server_health_check,
)
from .server_info import (
    handle_get_server_info,
    handle_update_guild,
    handle_list_members,
    handle_list_servers,
)
from .topology import (
    handle_topology_channel_children,
    handle_topology_channel_tree,
    handle_topology_permission_matrix,
    handle_topology_role_hierarchy,
)
from .channel_advanced import (
    handle_clone_channel,
    handle_create_announcement_channel,
    handle_create_stage_channel,
    handle_follow_channel,
    handle_set_voice_channel_status,
    handle_sync_channel_permissions,
)
from .invites_membership import (
    handle_create_invite,
    handle_delete_invite,
    handle_estimate_pruned_members,
    handle_get_ban,
    handle_get_role_member_counts,
    handle_list_bans,
    handle_list_invites,
    handle_search_members,
)
from .messages_advanced import (
    handle_clear_message_reactions,
    handle_create_thread_from_message,
    handle_forward_message,
    handle_get_poll_results,
    handle_get_reaction_users,
    handle_pin_message,
    handle_send_components,
    handle_send_message_with_files,
    handle_send_poll,
    handle_send_typing,
    handle_unpin_message,
)
from .thread_management import (
    handle_add_thread_member,
    handle_create_thread,
    handle_delete_thread,
    handle_edit_thread,
    handle_join_thread,
    handle_leave_thread,
    handle_list_active_threads,
    handle_remove_thread_member,
)
from .emoji_sticker_soundboard import (
    handle_create_application_emoji,
    handle_create_emoji,
    handle_create_soundboard_sound,
    handle_create_sticker,
    handle_delete_application_emoji,
    handle_delete_emoji,
    handle_delete_soundboard_sound,
    handle_delete_sticker,
    handle_edit_application_emoji,
    handle_edit_emoji,
    handle_edit_soundboard_sound,
    handle_edit_sticker,
    handle_list_application_emojis,
    handle_list_soundboard_sounds,
    handle_list_stickers,
    handle_send_soundboard_sound,
)
from .members_roles_advanced import (
    handle_change_member_voice_state,
    handle_create_dm_channel,
    handle_edit_member_profile,
    handle_get_member_voice_state,
    handle_get_role_details,
    handle_move_member_voice,
    handle_reorder_roles,
    handle_request_to_speak,
    handle_set_role_icon,
    handle_update_bot_profile,
)
from .monetization_appcmds import (
    handle_consume_entitlement,
    handle_create_entitlement,
    handle_delete_entitlement,
    handle_get_app_command,
    handle_get_entitlement,
    handle_list_app_commands,
    handle_list_entitlements,
    handle_list_skus,
    handle_sync_app_commands,
)
from .scheduled_stage import (
    handle_cancel_scheduled_event,
    handle_create_scheduled_event,
    handle_create_stage_instance,
    handle_delete_scheduled_event,
    handle_delete_stage_instance,
    handle_edit_scheduled_event,
    handle_edit_stage_instance,
    handle_end_scheduled_event,
    handle_get_scheduled_event,
    handle_get_stage_instance,
    handle_list_scheduled_event_users,
    handle_list_scheduled_events,
    handle_start_scheduled_event,
)
from .webhook_mgmt import (
    handle_delete_webhook,
    handle_delete_webhook_message,
    handle_edit_webhook,
    handle_edit_webhook_message,
    handle_get_webhook,
    handle_get_webhook_message,
)
from .templates_widget import (
    handle_create_template,
    handle_delete_template,
    handle_edit_template,
    handle_edit_widget_settings,
    handle_get_guild_preview,
    handle_get_template,
    handle_get_widget_settings,
    handle_list_templates,
    handle_sync_template,
)


Handler = Callable[[Dict[str, Any], Dict[str, Any]], Awaitable[List[TextContent]]]


TOOL_ROUTER: Dict[str, Handler] = {
    "send_message": handle_send_message,
    "send-message": handle_send_message,
    "read_messages": handle_read_messages,
    "read-messages": handle_read_messages,
    "edit_message": handle_edit_message,
    "edit-message": handle_edit_message,
    "reply_message": handle_reply_message,
    "reply-message": handle_reply_message,
    "read_forum_threads": handle_read_forum_threads,
    "read-forum-threads": handle_read_forum_threads,
    "list_threads": handle_list_threads,
    "list-threads": handle_list_threads,
    "search_threads": handle_search_threads,
    "search-threads": handle_search_threads,
    "add_thread_tags": handle_add_thread_tags,
    "add-thread-tags": handle_add_thread_tags,
    "unarchive_thread": handle_unarchive_thread,
    "unarchive-thread": handle_unarchive_thread,
    "list_forum_posts": handle_list_forum_posts,
    "read_forum_post_messages": handle_read_forum_post_messages,
    "read_forum_posts_batch": handle_read_forum_posts_batch,
    "get_thread_context": handle_get_thread_context,
    "list_thread_participants": handle_list_thread_participants,
    "get_thread_activity_summary": handle_get_thread_activity_summary,
    "tag_forum_post": handle_tag_forum_post,
    "retag_forum_post": handle_retag_forum_post,
    "moderation_bulk_delete": handle_moderation_bulk_delete,
    "moderation_timeout_member": handle_moderation_timeout_member,
    "moderation_kick_member": handle_moderation_kick_member,
    "moderation_ban_member": handle_moderation_ban_member,
    "topology_channel_tree": handle_topology_channel_tree,
    "topology_channel_children": handle_topology_channel_children,
    "topology_role_hierarchy": handle_topology_role_hierarchy,
    "topology_permission_matrix": handle_topology_permission_matrix,
    "download_attachment": handle_download_attachment,
    "download-attachment": handle_download_attachment,
    "get_user_info": handle_get_user_info,
    "moderate_message": handle_moderate_message,
    "get_server_info": handle_get_server_info,
    "update_guild": handle_update_guild,
    "get_channels": handle_get_channels,
    "list_members": handle_list_members,
    "add_role": handle_add_role,
    "remove_role": handle_remove_role,
    "create_text_channel": handle_create_text_channel,
    "create_voice_channel": handle_create_voice_channel,
    "create-voice-channel": handle_create_voice_channel,
    "create_forum_channel": handle_create_forum_channel,
    "create-forum-channel": handle_create_forum_channel,
    "delete_channel": handle_delete_channel,
    "update_text_channel": handle_update_text_channel,
    "update-text-channel": handle_update_text_channel,
    "update_voice_channel": handle_update_voice_channel,
    "update-voice-channel": handle_update_voice_channel,
    "update_forum_channel": handle_update_forum_channel,
    "update-forum-channel": handle_update_forum_channel,
    "add_reaction": handle_add_reaction,
    "add_multiple_reactions": handle_add_multiple_reactions,
    "remove_reaction": handle_remove_reaction,
    "get_guild_welcome_screen": handle_get_guild_welcome_screen,
    "update_guild_welcome_screen": handle_update_guild_welcome_screen,
    "get_guild_onboarding": handle_get_guild_onboarding,
    "update_guild_onboarding": handle_update_guild_onboarding,
    "dynamic_role_provision": handle_dynamic_role_provision,
    "verification_gate_orchestrator": handle_verification_gate_orchestrator,
    "progressive_access_unlock": handle_progressive_access_unlock,
    "onboarding_friction_audit": handle_onboarding_friction_audit,
    "send_embed_message": handle_send_embed_message,
    "send_rich_announcement": handle_send_rich_announcement,
    "crosspost_announcement": handle_crosspost_announcement,
    "create_channel_webhook": handle_create_channel_webhook,
    "list_channel_webhooks": handle_list_channel_webhooks,
    "execute_channel_webhook": handle_execute_channel_webhook,
    "list_guild_integrations": handle_list_guild_integrations,
    "get_guild_vanity_url": handle_get_guild_vanity_url,
    "list_servers": handle_list_servers,
    "get_channels_structured": handle_get_channels_structured,
    "get_channel_hierarchy": handle_get_channel_hierarchy,
    "get_role_hierarchy": handle_get_role_hierarchy,
    "get_permission_overwrites": handle_get_permission_overwrites,
    "set_channel_permission_overwrite": handle_set_channel_permission_overwrite,
    "remove_channel_permission_overwrite": handle_remove_channel_permission_overwrite,
    "diff_channel_permissions": handle_diff_channel_permissions,
    "export_server_snapshot": handle_export_server_snapshot,
    "get_channel_type_counts": handle_get_channel_type_counts,
    "list_inactive_channels": handle_list_inactive_channels,
    "create_role": handle_create_role,
    "delete_role": handle_delete_role,
    "update_role": handle_update_role,
    "add_roles_bulk": handle_add_roles_bulk,
    "remove_roles_bulk": handle_remove_roles_bulk,
    "mute_member_role_based": handle_mute_member_role_based,
    "unmute_member_role_based": handle_unmute_member_role_based,
    "permission_drift_check": handle_permission_drift_check,
    "get_audit_log": handle_get_audit_log,
    "get_member_moderation_history": handle_get_member_moderation_history,
    "get_channel_activity_summary": handle_get_channel_activity_summary,
    "get_incident_timeline": handle_get_incident_timeline,
    "get_audit_actor_summary": handle_get_audit_actor_summary,
    "check_audit_reason_compliance": handle_check_audit_reason_compliance,
    "server_health_check": handle_server_health_check,
    "governance_evidence_packager": handle_governance_evidence_packager,
    "incident_get_channel_state": handle_incident_get_channel_state,
    "incident-get-channel-state": handle_incident_get_channel_state,
    "incident_set_channel_state": handle_incident_set_channel_state,
    "incident-set-channel-state": handle_incident_set_channel_state,
    "incident_apply_lockdown": handle_incident_apply_lockdown,
    "incident-apply-lockdown": handle_incident_apply_lockdown,
    "incident_rollback_lockdown": handle_incident_rollback_lockdown,
    "incident-rollback-lockdown": handle_incident_rollback_lockdown,
    "automod_validate_ruleset": handle_automod_validate_ruleset,
    "automod-validate-ruleset": handle_automod_validate_ruleset,
    "automod_get_ruleset": handle_automod_get_ruleset,
    "automod-get-ruleset": handle_automod_get_ruleset,
    "automod_apply_ruleset": handle_automod_apply_ruleset,
    "automod-apply-ruleset": handle_automod_apply_ruleset,
    "automod_rollback_ruleset": handle_automod_rollback_ruleset,
    "automod-rollback-ruleset": handle_automod_rollback_ruleset,
    "bulk_ban_members": handle_bulk_ban_members,
    "prune_inactive_members": handle_prune_inactive_members,
    "remove_member_timeout": handle_remove_member_timeout,
    "unban_member": handle_unban_member,
    "create_category": handle_create_category,
    "rename_category": handle_rename_category,
    "move_category": handle_move_category,
    "delete_category": handle_delete_category,
    "create_incident_room": handle_create_incident_room,
    "append_incident_event": handle_append_incident_event,
    "close_incident": handle_close_incident,
    "list_auto_moderation_rules": handle_list_auto_moderation_rules,
    "create_auto_moderation_rule": handle_create_auto_moderation_rule,
    "update_auto_moderation_rule": handle_update_auto_moderation_rule,
    "delete_auto_moderation_rule": handle_delete_auto_moderation_rule,
    "automod_export_rules": handle_automod_export_rules,
    "get_role_permissions": handle_get_role_permissions,
    "compute_member_permissions": handle_compute_member_permissions,
    "audit_mass_mentions": handle_audit_mass_mentions,
    "set_member_nickname": handle_set_member_nickname,
    "set_member_roles": handle_set_member_roles,
    "list_guild_emojis": handle_list_guild_emojis,
    # --- discord.py coverage-gap domains (docs/product/coverage-gaps-implementation.md) ---
    "create_invite": handle_create_invite,
    "list_invites": handle_list_invites,
    "delete_invite": handle_delete_invite,
    "list_bans": handle_list_bans,
    "get_ban": handle_get_ban,
    "search_members": handle_search_members,
    "get_role_member_counts": handle_get_role_member_counts,
    "estimate_pruned_members": handle_estimate_pruned_members,
    "create_thread": handle_create_thread,
    "join_thread": handle_join_thread,
    "leave_thread": handle_leave_thread,
    "add_thread_member": handle_add_thread_member,
    "remove_thread_member": handle_remove_thread_member,
    "edit_thread": handle_edit_thread,
    "delete_thread": handle_delete_thread,
    "list_active_threads": handle_list_active_threads,
    "send_message_with_files": handle_send_message_with_files,
    "send_components": handle_send_components,
    "send_poll": handle_send_poll,
    "get_poll_results": handle_get_poll_results,
    "forward_message": handle_forward_message,
    "pin_message": handle_pin_message,
    "unpin_message": handle_unpin_message,
    "clear_message_reactions": handle_clear_message_reactions,
    "get_reaction_users": handle_get_reaction_users,
    "create_thread_from_message": handle_create_thread_from_message,
    "send_typing": handle_send_typing,
    "clone_channel": handle_clone_channel,
    "create_announcement_channel": handle_create_announcement_channel,
    "create_stage_channel": handle_create_stage_channel,
    "follow_channel": handle_follow_channel,
    "sync_channel_permissions": handle_sync_channel_permissions,
    "set_voice_channel_status": handle_set_voice_channel_status,
    "change_member_voice_state": handle_change_member_voice_state,
    "move_member_voice": handle_move_member_voice,
    "request_to_speak": handle_request_to_speak,
    "get_member_voice_state": handle_get_member_voice_state,
    "edit_member_profile": handle_edit_member_profile,
    "create_dm_channel": handle_create_dm_channel,
    "update_bot_profile": handle_update_bot_profile,
    "set_role_icon": handle_set_role_icon,
    "reorder_roles": handle_reorder_roles,
    "get_role_details": handle_get_role_details,
    "create_emoji": handle_create_emoji,
    "edit_emoji": handle_edit_emoji,
    "delete_emoji": handle_delete_emoji,
    "create_application_emoji": handle_create_application_emoji,
    "edit_application_emoji": handle_edit_application_emoji,
    "delete_application_emoji": handle_delete_application_emoji,
    "list_application_emojis": handle_list_application_emojis,
    "create_sticker": handle_create_sticker,
    "edit_sticker": handle_edit_sticker,
    "delete_sticker": handle_delete_sticker,
    "list_stickers": handle_list_stickers,
    "create_soundboard_sound": handle_create_soundboard_sound,
    "list_soundboard_sounds": handle_list_soundboard_sounds,
    "edit_soundboard_sound": handle_edit_soundboard_sound,
    "delete_soundboard_sound": handle_delete_soundboard_sound,
    "send_soundboard_sound": handle_send_soundboard_sound,
    "get_webhook": handle_get_webhook,
    "edit_webhook": handle_edit_webhook,
    "delete_webhook": handle_delete_webhook,
    "get_webhook_message": handle_get_webhook_message,
    "edit_webhook_message": handle_edit_webhook_message,
    "delete_webhook_message": handle_delete_webhook_message,
    "create_scheduled_event": handle_create_scheduled_event,
    "get_scheduled_event": handle_get_scheduled_event,
    "list_scheduled_events": handle_list_scheduled_events,
    "edit_scheduled_event": handle_edit_scheduled_event,
    "delete_scheduled_event": handle_delete_scheduled_event,
    "start_scheduled_event": handle_start_scheduled_event,
    "end_scheduled_event": handle_end_scheduled_event,
    "cancel_scheduled_event": handle_cancel_scheduled_event,
    "list_scheduled_event_users": handle_list_scheduled_event_users,
    "create_stage_instance": handle_create_stage_instance,
    "get_stage_instance": handle_get_stage_instance,
    "edit_stage_instance": handle_edit_stage_instance,
    "delete_stage_instance": handle_delete_stage_instance,
    "list_skus": handle_list_skus,
    "list_entitlements": handle_list_entitlements,
    "get_entitlement": handle_get_entitlement,
    "create_entitlement": handle_create_entitlement,
    "consume_entitlement": handle_consume_entitlement,
    "delete_entitlement": handle_delete_entitlement,
    "list_app_commands": handle_list_app_commands,
    "get_app_command": handle_get_app_command,
    "sync_app_commands": handle_sync_app_commands,
    "list_templates": handle_list_templates,
    "create_template": handle_create_template,
    "get_template": handle_get_template,
    "sync_template": handle_sync_template,
    "edit_template": handle_edit_template,
    "delete_template": handle_delete_template,
    "get_guild_preview": handle_get_guild_preview,
    "get_widget_settings": handle_get_widget_settings,
    "edit_widget_settings": handle_edit_widget_settings,
}


async def dispatch_tool_call(
    name: str, arguments: Dict[str, Any], deps: Dict[str, Any]
) -> List[TextContent]:
    handler = TOOL_ROUTER.get(name)
    if handler is None:
        raise ValueError(f"Unknown tool: {name}")
    return await handler(arguments, deps)
